version: 0.2

# AWS CodeBuild buildspec for staging deployment
# This file defines the build process for deploying the customer-service to staging environment

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCOUNT_ID: "123456789012"  # Replace with your AWS Account ID
    ECR_REPOSITORY: customer-service
    ECS_CLUSTER_NAME: customer-service-staging
    ECS_SERVICE_NAME: customer-service-staging
    CONTAINER_NAME: customer-service
  parameter-store:
    # Store sensitive values in AWS Systems Manager Parameter Store
    DB_HOST: /customer-service/staging/db/host
    DB_PASSWORD: /customer-service/staging/db/password
  secrets-manager:
    # Store highly sensitive values in AWS Secrets Manager
    API_SECRET_KEY: customer-service/staging:api_secret_key

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - echo Repository URI is $REPOSITORY_URI
      - echo Image tag is $IMAGE_TAG
      
  build:
    commands:
      - echo Build started on `date`
      - echo Updating ECS service with new image...
      - |
        # Create new task definition with updated image
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $ECS_SERVICE_NAME --query 'taskDefinition')
        NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$REPOSITORY_URI:$IMAGE_TAG" '.containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.placementConstraints) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)')
        NEW_TASK_INFO=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
        NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
        
      - echo Updating ECS service...
      - |
        aws ecs update-service \
          --cluster $ECS_CLUSTER_NAME \
          --service $ECS_SERVICE_NAME \
          --task-definition $ECS_SERVICE_NAME:$NEW_REVISION
          
      - echo Waiting for service to become stable...
      - |
        aws ecs wait services-stable \
          --cluster $ECS_CLUSTER_NAME \
          --services $ECS_SERVICE_NAME
          
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deployment to staging completed successfully
      - |
        # Get service details for verification
        SERVICE_INFO=$(aws ecs describe-services --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME)
        RUNNING_COUNT=$(echo $SERVICE_INFO | jq '.services[0].runningCount')
        DESIRED_COUNT=$(echo $SERVICE_INFO | jq '.services[0].desiredCount')
        echo "Service Status: Running=$RUNNING_COUNT, Desired=$DESIRED_COUNT"
        
      - |
        # Optional: Run health checks
        echo "Running health checks..."
        # Add your health check commands here
        # Example: curl -f http://your-staging-endpoint/health || exit 1
        
artifacts:
  files:
    - '**/*'
  name: customer-service-staging-deployment
  
cache:
  paths:
    - '/root/.m2/**/*'