phases:
  pre_build:
    commands:
      - echo "SOURCE LOCATION:"
      - echo "$CODEBUILD_SOURCE_LOCATION"
      - echo "WEBHOOK SOURCE LOCATION:"
      - echo "$CODEBUILD_DEFAULT_WEBHOOK_SOURCE_LOCATION"
