version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Starting build..."
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - target/*.jar
